import { config } from '../config.js';
import {
  getRecentGradedProperties,
  type GradedProperty,
} from '../db/grades.js';
import { recordAlertSent } from '../db/alerts.js';
import { getInvestorProfile, filterByProfile } from './profile-filter.js';
import {
  toNotificationItem,
  fmtMoney,
  fmtPct,
  fmtPriceSqft,
  fmtBedsBaths,
  fmtSqft,
  fmtType,
  type NotificationItem,
} from './format.js';
import type { Letter } from '../scoring/types.js';

/**
 * Daily email digest via SendGrid. Includes every property graded in the last
 * 24h, grouped by grade (A first, then B…F), rendered as HTML. Unlike Slack
 * this always sends — it's a once-a-day summary, not a per-event alert — and
 * logs each included property to alerts_sent for an audit trail.
 */

const ALERT_TYPE = 'daily_digest';
const CHANNEL = 'email';
const GRADE_ORDER: Letter[] = ['A', 'B', 'C', 'D', 'F'];

// Hardcoded grade colors — identical to the dashboard (src/dashboard/lib/format.ts
// GRADE_HEX) so a grade looks the same in the email as in the app. The grade
// badge is a colored circle with white text. A=green, B=blue, C=yellow,
// D=orange, F=red.
const GRADE_COLOR: Record<Letter, string> = {
  A: '#16a34a',
  B: '#2563eb',
  C: '#ca8a04',
  D: '#ea580c',
  F: '#dc2626',
};

/** A colored circle badge with white text, inline-table for email-client support. */
function gradeBadgeHtml(grade: Letter | string, color: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="display:inline-table"><tr><td align="center" valign="middle" width="24" height="24" style="width:24px;height:24px;background-color:${color};border-radius:12px;color:#ffffff;font-size:13px;font-weight:700;line-height:24px;text-align:center">${grade}</td></tr></table>`;
}

export interface EmailSendSummary {
  total: number;
  aCount: number;
  subject: string;
}

/**
 * Build and send the daily digest. By default it covers the last 24 hours; pass
 * `sinceHours` to widen the window (the test script uses a large value to pull
 * in existing data). Returns a summary even when nothing was graded.
 */
export async function sendEmailDigest(
  opts: { sinceHours?: number; dryRun?: boolean } = {},
): Promise<EmailSendSummary> {
  const sinceHours = opts.sinceHours ?? 24;
  // Apply the same investor-profile filters the dashboard uses, across all
  // grades — the digest never includes a property hidden on the dashboard.
  const properties = filterByProfile(
    await getRecentGradedProperties(sinceHours),
    await getInvestorProfile(),
  );
  const items = await Promise.all(properties.map(toNotificationItem));

  const date = todayLabel();
  const aCount = properties.filter((p) => p.overall_grade === 'A').length;
  const subject = buildSubject(date, properties.length, aCount);
  const html = buildDigestHtml(items, date);

  if (opts.dryRun) {
    console.log(`[dry-run] subject: ${subject}`);
    console.log(`[dry-run] ${properties.length} properties, ${aCount} grade A`);
  } else {
    await sendViaSendGrid(subject, html);
    for (const p of properties) {
      await recordAlertSent(p.listing_id, CHANNEL, ALERT_TYPE);
    }
  }

  return { total: properties.length, aCount, subject };
}

export function buildSubject(
  date: string,
  total: number,
  aCount: number,
): string {
  const props = `${total} new propert${total === 1 ? 'y' : 'ies'}`;
  const a = `${aCount} grade A opportunit${aCount === 1 ? 'y' : 'ies'}`;
  return `🏠 Real Estate Daily Digest - ${date} - ${props}, ${a}`;
}

/** Render the full HTML email: a section per grade, each a table of properties. */
export function buildDigestHtml(items: NotificationItem[], date: string): string {
  const byGrade = groupByGrade(items);

  const sections = GRADE_ORDER.filter((g) => byGrade[g]?.length).map((g) =>
    gradeSection(g, byGrade[g] ?? []),
  );

  const body =
    items.length === 0
      ? `<p style="color:#57606a">No new properties were graded in the last 24 hours.</p>`
      : sections.join('\n');

  const dashboardUrl = config.dashboardUrl;
  const dashboardLink = dashboardUrl
    ? `<div style="font-size:13px;margin-bottom:20px"><a href="${encodeURI(dashboardUrl)}" style="color:#0969da">📊 View Dashboard: ${escapeHtml(dashboardUrl)}</a></div>`
    : '';

  return `<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f6f8fa;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1f2328">
  <div style="max-width:680px;margin:0 auto;padding:24px">
    <h1 style="font-size:20px;margin:0 0 4px">🏠 Real Estate Daily Digest</h1>
    <div style="color:#57606a;font-size:13px;margin-bottom:4px">${escapeHtml(date)} · ${items.length} new propert${items.length === 1 ? 'y' : 'ies'}</div>
    ${dashboardLink}
    ${body}
    <div style="color:#8c959f;font-size:11px;margin-top:28px;border-top:1px solid #d0d7de;padding-top:12px">
      Generated by Real Estate Tracker. Grades reflect cash-on-cash, cash flow, price/sqft, crime, and rental-demand components.
    </div>
  </div>
</body>
</html>`;
}

function gradeSection(grade: Letter, items: NotificationItem[]): string {
  const color = GRADE_COLOR[grade];
  const rows = items.map((it) => propertyRow(it, color)).join('\n');
  return `
  <div style="margin-bottom:24px">
    <h2 style="font-size:15px;margin:0 0 10px;color:${color}">
      Grade ${grade} <span style="color:#57606a;font-weight:normal">(${items.length})</span>
    </h2>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
      ${rows}
    </table>
  </div>`;
}

function propertyRow(item: NotificationItem, color: string): string {
  const p = item.property;
  const address = escapeHtml(p.address ?? p.city ?? `Listing ${p.listing_id}`);
  const sub = [
    `${escapeHtml(fmtType(p.property_type))}`,
    `${escapeHtml(fmtBedsBaths(p))} bd/ba`,
    `${escapeHtml(fmtSqft(p))} sqft`,
    p.price != null ? escapeHtml(fmtMoney(p.price)) : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return `
      <tr>
        <td style="padding:12px;border:1px solid #d0d7de;border-radius:6px;background:#ffffff">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td style="font-size:14px;font-weight:600">${address}</td>
              <td align="right">${gradeBadgeHtml(p.overall_grade, color)}</td>
            </tr>
            <tr><td colspan="2" style="font-size:12px;color:#57606a;padding-top:2px">${sub}</td></tr>
            <tr><td colspan="2" style="font-size:13px;padding-top:8px">
              <strong>CoC:</strong> ${escapeHtml(fmtPct(p.coc_return))} &nbsp;·&nbsp;
              <strong>Cash flow:</strong> ${escapeHtml(fmtMoney(p.monthly_cashflow))}/mo &nbsp;·&nbsp;
              <strong>Price/sqft:</strong> ${escapeHtml(fmtPriceSqft(item))}
            </td></tr>
            <tr><td colspan="2" style="font-size:13px;padding-top:8px">${linkAnchor(item)}</td></tr>
          </table>
        </td>
      </tr>
      <tr><td style="height:10px"></td></tr>`;
}

function linkAnchor(item: NotificationItem): string {
  if (item.zillowUrl) {
    return `🔗 <a href="${encodeURI(item.zillowUrl)}" style="color:#0969da">View on Zillow</a>`;
  }
  if (item.realtorUrl) {
    return `🔗 <a href="${encodeURI(item.realtorUrl)}" style="color:#0969da">View on Realtor.com</a>`;
  }
  return `<span style="color:#8c959f">No listing link available</span>`;
}

function groupByGrade(
  items: NotificationItem[],
): Partial<Record<Letter, NotificationItem[]>> {
  const out: Partial<Record<Letter, NotificationItem[]>> = {};
  for (const it of items) {
    const g = it.property.overall_grade as Letter;
    (out[g] ??= []).push(it);
  }
  return out;
}

/** POST to the SendGrid v3 mail/send endpoint. 202 = accepted. */
export async function sendViaSendGrid(subject: string, html: string): Promise<void> {
  const to = config.sendgridToEmails.map((email) => ({ email }));
  const payload = {
    personalizations: [{ to }],
    from: { email: config.sendgridFromEmail },
    subject,
    content: [{ type: 'text/html', value: html }],
  };

  const res = await fetch('https://api.sendgrid.com/v3/mail/send', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${config.sendgridApiKey}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(30_000),
  });

  if (res.status !== 202) {
    const body = await res.text().catch(() => '');
    throw new Error(
      `SendGrid send failed: HTTP ${res.status} ${body.slice(0, 300)}`,
    );
  }
}

function todayLabel(): string {
  return new Date().toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
